fix: fixed userstory bugs
Iconica-Development/flutter_user pull request #82
Opened 2024-10-04 08:24 UTC by mighttymike

2025-04-14 13:57 UTC, bart-iconica requested changes

2025-04-14 13:57 UTC, bart-iconica commented on packages/flutter_user/lib/flutter_user.dart
> +// ignore: depend_on_referenced_packages
Don't just ignore these kind of things, simply add a dependency on the package. I'm assuming you can do this because somehow this package is pulled in transitively but things will break once that stops happening for some reason. _Always_ depend explicitly.

You should always check if is there is a way to resolve linter warnings rather than ignoring them.

2025-04-14 15:14 UTC, freekvandeven approved these changes

2025-04-15 07:18 UTC, merged

2025-04-15 07:25 UTC, bart-iconica reviewed
The third commit does way more than it says it does, please split those changes out next time.

Also, you asked me to re-review it but before I got the change you already merged it. I still want my comments to be resolved so please open a new PR that fixes them.

2025-04-15 07:25 UTC, bart-iconica commented on packages/firebase_user_repository/lib/src/firebase_user_repository.dart
> +      //remove password from values
This comment is completely useless.

2025-04-15 07:25 UTC, bart-iconica commented on packages/flutter_user/lib/flutter_user.dart
> +// ignore: depend_on_referenced_packages
Don't mark this as resolved when it's still there. Remove it from the commit that added it (the first of this PR), not in a later commit.

2025-04-15 07:25 UTC, bart-iconica commented on packages/flutter_user/lib/src/flutter_user_navigator_userstory.dart
>              // ignore: use_build_context_synchronously
I know you're doing this in the next commit but you're already adding a line here in the first commit, so fix the mounted check immediately rather than later.